### ISSUE TITLE
你好，问下可不可以在触发播放时去指定一首歌播放？

### ISSUE THREAD

**Issue by DrakLu** [MoePlayer/vue-aplayer#145]
比如在调用这个this.$refs.aplayer.play()时传入一个参数如歌名，去播放这首歌

**Comment by u3u** [comment]
只提供了基础接口，但你可以通过设置内部的 `currentMusic` 来指定一首[歌曲](https://aplayer.netlify.com/docs/options/#audio)

```js
// 比如将当前播放的歌曲切换到列表的第一首歌
this.$refs.aplayer.currentMusic = this.$refs.aplayer.currentList[0];

// 播放指定歌曲
this.$refs.aplayer.currentMusic = this.$refs.aplayer.currentList.find((audio) =>
  audio.name.includes('歌曲名称')
);
```

**Comment by DrakLu** [comment]
嗯，谢谢！！！！！！

**Comment by u3u** [comment]
😅 抱歉，之前的版本漏了一个 [`switch`](https://aplayer.moefe.org/docs/api/#switch) API
更新到最新版后你可以使用它来切换歌曲，并且不推荐手动设置 `currentMusic` 来切换歌曲

**Comment by DrakLu** [comment]
嗯嗯，知道了，谢谢！
