### ISSUE TITLE
Autoplay 失败

### ISSUE THREAD

**Issue by subdance** [MoePlayer/vue-aplayer#146]
会提示
play() failed because the user didn;t interact with document.
我是在pc端的chrome打开的

**Comment by u3u** [comment]
Chrome 的自动播放政策很简单：

- 始终允许静音自动播放。
- 如果符合以下条件，则允许自动播放：
  - 用户已与域进行了互动（点击，tap 等）。
  - 在桌面上，用户的[媒体参与度指数](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#mei)阈值已超过，这意味着用户之前已播放带有声音的视频。
  - 在移动设备上，用户已[将网站添加到其主屏幕]。
- 顶部框架可以[将自动播放权限委托](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#iframe)给他们的 iframe，以允许自动播放声音。

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by subdance** [comment]
十分感谢！🐰☕
