### ISSUE TITLE
删除播放列表的item， 当前歌曲改变 emit 事件

### ISSUE THREAD

**Issue by magicknight** [MoePlayer/vue-aplayer#4]
可以在每个item后面放个垃圾箱图标，点击就从列表里移除该item吗？然后有个按钮可以 all clear 所有的item。虽然可以在播放器之外给 array 做操作，但能在播放器里面删除似乎更自然些。

然后当前歌曲改变的话，能不能 emit 一个事件，并附上当前歌曲的index？

如果需要的话我可以提交一个patch，不过没学过ts，得花点时间。

**Comment by u3u** [comment]
移除当前歌曲的功能我可以添加 不过清除播放列表的话 这个按钮不知道加在哪里诶
当前歌曲改变 您可以监听 `play` 事件或者监听 `this.$refs.aplayer.currentMusic` 属性
然后通过 `this.$refs.aplayer.playIndex` 可以获取当前播放歌曲的索引
如果这两种方式都不能满足您的需求 我可以考虑添加一个事件

**Comment by magicknight** [comment]
好的，我看到在item 里面加入了删除图标，还有 'remove' 这个 prop。。。。
这个改动就能满足我的需求，非常感谢！
