### ISSUE TITLE
porp :music problem

### ISSUE THREAD

**Issue by woolninesun** [MoePlayer/vue-aplayer#65]
看 Aplayer 的 docu ,music 應該是對應到 audio 的部分
但 audio 的描述寫 audio info, should be an object or object array

嘗試加進一個object array 會報錯, error 表示只能是 object, 
看 type 資料夾裡的定義，好像就真的只能是一個 object。

這樣的話只能傳一首歌進去，那該怎麽建立一個歌單？

**Comment by u3u** [comment]
[`music`](https://github.com/MoePlayer/vue-aplayer/blob/master/docs/usage.md#props) 属性可以传递一个符合 [`music`](https://github.com/MoePlayer/vue-aplayer/blob/master/docs/usage.md#props) 对象的数组，如果无法解决，可以贴一下你的代码

并且很遗憾的是 1.x 版本不再维护，而 2.0 因为这个[问题](https://github.com/vuejs/vue-cli/issues/1607)将延期发布
如果您时间有限，或许您可以先尝试使用另一个 [vue-aplayer](https://github.com/SevenOutman/vue-aplayer)，感谢您的反馈！

**Comment by woolninesun** [comment]
thank! 我試試看另一個 vue-aplayer
