### ISSUE TITLE
[WIP] 2.0.0-beta.1

### ISSUE THREAD

**Issue by u3u** [MoePlayer/vue-aplayer#7]
_2.0 版本基于 APlayer v1.10.1 最新版重写，尽量与 APlayer 保持一致，最小化差异_

**新功能**

- [x] 吸底模式
- [x] 固定模式与迷你模式结合
- [x] 根据封面自适应主题色
- [x] 可配置播放器设置的 localStorage key
- [x] 加载状态
- [x] 通知消息
- [x] HLS 支持

**改进**

- [x] 多实例支持 (#3)
- [x] 新版示例页面
- [x] 新版文档，调研 [VuePress](https://vuepress.vuejs.org/)

**BUG 修复**

- [x] 手机端拖动播放小圆圈出现报错 (#6)

**破坏性更改**

- 现在需要传递 `lrcType` 来指定歌词使用什么方式获取
- 移除播放列表删除歌曲功能
- `fold` 重命名为 `listFolded`
- `listmaxheight` 重命名为 `listMaxHeight`

**工作流**

- 升级 `@vue/cli` 到 3.0.0-rc.10
- 使用 eslint 代替 tslint
- 使用 prettier 统一代码风格

**完成进度**

- [x] 播放器基础功能
  - [x] 新版布局和样式
  - [x] 数据双向绑定
  - [x] 基本交互
- [x] 核心功能（与 Audio 对象相关功能）
  - [x] 播放音频
  - [x] 歌词同步
  - [x] 调整音量
  - [x] 调整进度
  - [x] 调整速度
  - [x] 切换歌曲
  - [x] 上一曲
  - [x] 下一曲
  - [x] 循环模式（列表循环 / 单曲循环 / 不循环）
  - [x] 播放模式（顺序播放 / 随机播放）
  - [x] 公开接口
  - [x] 事件绑定
  - [x] 默认封面
  - [x] 保存播放器设置
  - [x] 另一个实例播放时是否暂停其他实例

**Comment by u3u** [comment]
核心功能代码可以在 [feat/core](https://github.com/MoePlayer/vue-aplayer/tree/feat/core) 分支查看。由于 `@vue/cli` 中的 `vue-cli-service build`  命令在生产环境下对 `jsx` 识别有[问题](https://github.com/vuejs/vue-cli/issues/1367)，导致 netlify 无法部署。所以在该问题被修复之前不会提交 Pull request

**Comment by u3u** [comment]
在 `@vue/cli-beta.12` 中[已修复](https://github.com/vuejs/vue-cli/blob/dev/CHANGELOG.md#300-beta12-2018-05-29)此问题，预览版可以在这里查看：
https://deploy-preview-20--aplayer.netlify.com

**Comment by kevin93d** [comment]
大大 2.0什么时候release啊 😭

**Comment by u3u** [comment]
@kevin93d 
快了快了 这周末把文档写好再优化一下代码 然后等待 `@vue/cli` 3.0.0-rc.6 发布我就可以发布了 😂

**Comment by kevin93d** [comment]
@u3u 
有点小激动🙊感谢大大

**Comment by u3u** [comment]
@kevin93d 
抱歉，久等了！已发布 beta 版本，欢迎体验 🎉
懒癌晚期加强迫症想把文档写得好一些 ( •̣̣̣̣̣̥́௰•̣̣̣̣̣̥̀ )
